<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version>1.0.0-beta.1</Version>
	  <PackageId>EventStoreCore.Postgres</PackageId>
	  <Authors>Edvard Jinder</Authors>
	  <Company>Intromedia Digital AB</Company>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	  <Description>PostgreSQL EF Core persistence configuration for EventStoreCore.</Description>
	  <PackageTags>eventstore event-sourcing efcore postgresql npgsql</PackageTags>
	  <PackageProjectUrl>https://github.com/EdvardJinder/eventstore</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/EdvardJinder/eventstore</RepositoryUrl>
	  <RepositoryType>git</RepositoryType>
	  <PackageReadmeFile>README.md</PackageReadmeFile>

  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\EventStoreCore.Abstractions\EventStoreCore.Abstractions.csproj" />
    <ProjectReference Include="..\EventStoreCore\EventStoreCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Update="Migrations\*.sql" Pack="true" PackagePath="migrations\" />
  </ItemGroup>

</Project>
