// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IM.EventStore.Tests.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IM.EventStore.DbEvent", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("StreamId", "Version")
                        .HasName("pk_events");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_events_tenant_id");

                    b.HasIndex("StreamId", "TenantId");

                    b.HasIndex("TenantId", "StreamId")
                        .HasDatabaseName("ix_events_tenant_id_stream_id");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("ix_events_tenant_id_timestamp");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("ix_events_tenant_id_type");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("IM.EventStore.DbStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<long>("CurrentVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_streams");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_streams_tenant_id");

                    b.HasIndex("TenantId", "CreatedTimestamp")
                        .HasDatabaseName("ix_streams_tenant_id_created_timestamp");

                    b.HasIndex("TenantId", "CurrentVersion")
                        .HasDatabaseName("ix_streams_tenant_id_version");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_streams_tenant_id_id");

                    b.HasIndex("TenantId", "UpdatedTimestamp")
                        .HasDatabaseName("ix_streams_tenant_id_updated_timestamp");

                    b.ToTable("streams", (string)null);
                });

            modelBuilder.Entity("IM.EventStore.DbSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CurrentSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("current_sequence");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_utc");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("SubscriptionType")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_subscription_type");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("OrderView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderView");
                });

            modelBuilder.Entity("IM.EventStore.DbEvent", b =>
                {
                    b.HasOne("IM.EventStore.DbStream", null)
                        .WithMany("Events")
                        .HasForeignKey("StreamId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IM.EventStore.DbStream", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
