<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0-beta.1</Version>
    <PackageId>EventStoreCore.Sqlite</PackageId>
    <Authors>Edvard Jinder</Authors>
    <Company>Intromedia Digital AB</Company>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Description>SQLite EF Core persistence configuration for EventStoreCore.</Description>
    <PackageTags>eventstore event-sourcing efcore sqlite</PackageTags>
    <PackageProjectUrl>https://github.com/EdvardJinder/eventstore</PackageProjectUrl>
    <RepositoryUrl>https://github.com/EdvardJinder/eventstore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventStoreCore\EventStoreCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
